name: gsy_github_app_flutter
description: Github Application


environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  fluttertoast: ^3.1.3
  json_annotation: ^3.0.0
  flutter_redux: ^0.5.3
  package_info: 0.4.0+6
  connectivity: 0.4.4
  flutter_markdown: 0.3.0
  share: ^0.6.2+3
  flutter_spinkit: ^4.0.0
  flutter_webview_plugin: ^0.3.8
  sqflite: ^1.1.7+1
  pub_semver: ^1.4.2
  flutter_svg: ^0.14.2
  flutter_slidable: ^0.5.3
  dio: ^3.0.3
  event_bus:  ^1.1.0
  flutter_cache_manager: ^1.1.1
  path_provider: ^1.3.0
  permission_handler: 3.2.2
  scoped_model: ^1.0.1
  rxdart: ^0.22.3
  webview_flutter: ^0.3.9+1
  bezier: ^1.1.2
  provider: ^3.1.0
  flare_flutter: ^1.6.1
  # 固定版本
  device_info: 0.4.0+3
  url_launcher: 5.1.2
  android_intent: 0.3.0
  shared_preferences: 0.5.3+4
  built_value: ^6.8.2
  graphql: ^2.0.0
  flutter_json_widget: 1.0.2
  flutter_localizations:
    sdk: flutter
  photo_view:
    git:
      url: https://github.com/CarSmallGuo/photo_view.git
      ref: master

dev_dependencies:
  build_runner: ^1.7.1
  built_value_generator: ^6.8.2
  json_serializable: ^3.2.3
#  flutter_test:
#    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

  assets:
    - static/images/
    - static/file/

  fonts:
    - family: wxcIconFont
      fonts:
        - asset: static/font/iconfont.ttf