name: gsy_github_app_flutter
description: Github Application
version: 1.7.0+32

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  fluttertoast: ^3.1.3
  flutter_redux: ^0.6.0
  share: ^0.6.2+5
  flutter_spinkit: ^4.1.1+1
  sqflite: ^1.2.0
  pub_semver: ^1.4.2
  flutter_svg: ^0.15.0
  flutter_slidable: ^0.5.4
  dio: ^3.0.7
  event_bus:  ^1.1.0
  flutter_cache_manager: ^1.1.3
  path_provider: ^1.5.1
  permission_handler: 3.2.2
  scoped_model: ^1.0.1
  flutter_webview_plugin: 0.3.10+1
  webview_flutter: ^0.3.19+8
  bezier: ^1.1.2
  provider: ^4.0.0
  flare_flutter: ^1.8.3
  # 固定版本
  json_annotation: 3.0.1
  package_info: 0.4.0+13
  connectivity: 0.4.6+1
  flutter_markdown: 0.3.3
  rxdart: 0.22.3
  device_info: 0.4.1+4
  url_launcher: 5.4.1
  google_fonts: 0.3.9
  android_intent: 0.3.4+8
  shared_preferences: 0.5.6
  built_value: 6.8.2
  graphql: 2.1.0
  flutter_json_widget: 1.0.2
  simple_animations: 1.3.4
  flutter_localizations:
    sdk: flutter
  photo_view:
    git:
      url: https://github.com/CarSmallGuo/photo_view.git
      ref: master

dev_dependencies:
  built_value_generator: 6.8.2
  build_runner: ^1.7.2
  json_serializable: 3.2.0
#  flutter_test:
#    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

  assets:
    - static/images/
    - static/file/

  fonts:
    - family: wxcIconFont
      fonts:
        - asset: static/font/iconfont.ttf
    - family: google_kavivanar
      fonts:
        - asset: static/font/google_kavivanar.ttf