name: gsy_github_app_flutter
description: Github Application

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.1+1
  fluttertoast: ^3.0.1
  json_annotation: ^2.0.0
  flutter_redux: ^0.5.3
  device_info: ^0.4.0+1
  connectivity: ^0.4.2
  url_launcher: ^5.0.1
  flutter_markdown: ^0.2.0
  share: ^0.6.0+1
  flutter_spinkit: ^3.1.0
  flutter_webview_plugin: ^0.2.1+2
  sqflite: ^1.1.1
  pub_semver: ^1.4.2
  flutter_statusbar: ^0.0.1
  flutter_svg: ^0.11.0+1
  photo_view: ^0.2.1
  flutter_slidable: ^0.4.9
  dio: ^2.0.15
  flutter_localizations:
    sdk: flutter
  event_bus:  ^1.0.3
  flutter_cache_manager: ^0.3.1
  path_provider: ^0.5.0+1
  permission_handler: 3.0.0
  scoped_model: ^1.0.1
  package_info: ^0.4.0+1

dev_dependencies:
  build_runner: ^1.2.8
  json_serializable: ^2.0.0
#  flutter_test:
#    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

  assets:
    - static/images/logo.png
    - static/images/welcome.png
    - static/images/default_img.png

  fonts:
    - family: wxcIconFont
      fonts:
        - asset: static/font/iconfont.ttf