name: gsy_github_app_flutter
description: Github Application
version: 1.7.0+32

environment:
  sdk: '>=2.12.0 <3.0.0'


dependency_overrides:
  analyzer: 1.1.0
  web_socket_channel: 2.0.0
  #pub_semver: 1.4.2
  #glob: 2.0.0
  #crypto: 3.0.0
  #args: 1.0.0
  #string_scanner: 1.1.0
  #convert: 1.0.0
  #rxdart: 0.25.0
  #http: 0.13.0
  #gql_http_link: 0.3.2
  #http_parser: 4.0.0

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  fluttertoast: ^8.0.1-nullsafety.0
  share: ^2.0.0
  flutter_spinkit: ^5.0.0
  sqflite: 2.0.0
  pub_semver: 2.0.0
  flutter_svg: 0.21.0-nullsafety.0
  flutter_slidable: ^0.6.0-nullsafety.0
  dio: 4.0.0-beta6
  path_provider: 2.0.0
  flutter_webview_plugin: 0.3.11
  webview_flutter: 2.0.0
  #bezier: ^1.1.5
  flare_flutter:  ^3.0.0-nullsafety.0
  # 固定版本
  flutter_redux: 0.8.0
  rxdart: 0.26.0
  graphql: 5.0.0-nullsafety.1+readmefix
  #flutter_cache_manager: 3.0.0-nullsafety.0
  provider: 5.0.0
  permission_handler: 6.0.1
  json_annotation: 4.0.0
  package_info: 2.0.0
  connectivity: 3.0.0
  flutter_markdown: 0.6.0
  device_info:  2.0.0
  url_launcher: 6.0.1
  google_fonts: 2.0.0
  android_intent: 2.0.0
  shared_preferences: 2.0.1
  built_value: 8.0.0
  simple_animations: 3.0.1
  supercharged: 2.0.0
  animations: 2.0.0
  auto_size_text: 3.0.0-nullsafety.0
  flutter_localizations:
    sdk: flutter
  photo_view: 0.11.1
#    git:
#      url: https://github.com/CarSmallGuo/photo_view.git
#      ref: master

dev_dependencies:
  built_value_generator: 8.0.0
  build_runner: ^1.11.5
  json_serializable: 4.0.2
#  flutter_test:
#    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

  assets:
    - static/images/
    - static/file/

  fonts:
    - family: wxcIconFont
      fonts:
        - asset: static/font/iconfont.ttf
    - family: google_kavivanar
      fonts:
        - asset: static/font/google_kavivanar.ttf