name: gsy_github_app_flutter
description: Github Application
version: 1.7.0+32

environment:
  sdk: '>=3.6.0 <4.0.0'


dependency_overrides:
#analyzer: 1.1.0
#web_socket_channel: 2.0.0
#pub_semver: 1.4.2
#glob: 2.0.0
#crypto: 3.0.0
#args: 1.0.0
#string_scanner: 1.1.0
#convert: 1.0.0
#rxdart: 0.25.0
#http: 0.13.0
#gql_http_link: 0.3.2
#http_parser: 4.0.0
# fix inappwebview R8 issue https://github.com/pichillilorenzo/flutter_inappwebview/issues/2193
#  flutter_inappwebview_android:
#    git:
#      url: https://github.com/holzgeist/flutter_inappwebview
#      path: flutter_inappwebview_android
#      ref: d89b1d32638b49dfc58c4b7c84153be0c269d057

dependencies:
  flutter:
    sdk: flutter
  intl: any

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  fluttertoast: 8.2.10
  share_plus: 7.1.0
  flutter_spinkit: 5.2.1
  sqflite: 2.3.3+1
  pub_semver: 2.1.4
  flutter_svg: 2.0.17
  flutter_slidable: 3.1.2
  dio: 5.6.0
  #fconsole: 2.2.1
  path_provider: 2.1.4
  webview_flutter: 4.10.0
  # é«˜ç‰ˆæœ¬ç›®å‰å’ŒðŸ‘†å…¼å®¹æœ‰é—®é¢˜
  flutter_inappwebview: 6.1.0+1
  #bezier: ^1.1.5
  flare_flutter:
    git:
      url: https://gitee.com/CarGuo/Flare-Flutter.git
      ref: d9c4ca55cbea3f283491679847ff1e9b4bc74192
      path: flare_flutter/

  rive: 0.13.13
  # å›ºå®šç‰ˆæœ¬
  easy_refresh: 3.4.0
  signals: 6.0.2
  flutter_redux: 0.10.0
  rxdart: 0.27.1
  graphql: 5.2.0
  #flutter_cache_manager: 3.0.0-nullsafety.0
  provider: 6.1.2
  permission_handler: 11.3.1
  json_annotation: 4.9.0
  package_info_plus: 8.0.2
  connectivity_plus: 6.0.5
  flutter_markdown: 0.7.6+2
  device_info_plus: 10.1.2
  url_launcher: 6.3.0
  google_fonts: 6.2.1
  android_intent_plus: 5.1.0
  shared_preferences: 2.3.1
  built_value: 8.9.2
  simple_animations: 5.0.2
  supercharged: 2.1.1
  animations: 2.0.11
  lottie: 3.0.0
  auto_size_text: 3.0.0
  flutter_localizations:
    sdk: flutter
  photo_view: 0.15.0
  #    git:
  #      url: https://github.com/CarSmallGuo/photo_view.git
  #      ref: master

  redux: any
  webview_flutter_android: any
  webview_flutter_wkwebview: any
  string_scanner: any
  meta: any
  flutter_riverpod: 2.6.1
  riverpod_annotation: 2.6.1
dev_dependencies:
  riverpod_generator: 2.6.1
  built_value_generator: 8.9.2
  build_runner: ^2.4.14
  json_serializable: 6.8.0
  flutter_lints: 4.0.0
#  flutter_test:
#    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # é’ˆå¯¹å¤šè¯­è¨€ l10n
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

  assets:
    - static/images/
    - static/file/

  fonts:
    - family: wxcIconFont
      fonts:
        - asset: static/font/iconfont.ttf
    - family: google_kavivanar
      fonts:
        - asset: static/font/google_kavivanar.ttf